Fix

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,6 +3,33 @@
 version: 2.1
 
 executors:
+  ubuntu-docker:
+    working_directory: /home/circleci/gogo/src/github.com/isindir/sops-secrets-operator
+    docker:
+      - image: ubuntu:16.04
+    environment:
+      K8S_VERSION: v1.16.3
+      KIND_VERSION: v0.6.1
+      HELM_VERSION: v2.16.1
+      GOLANG_VERSION: 1.13.4
+      OPERATOR_SDK_VERSION: v0.13.0
+      SOPS_VERSION: v3.5.0
+
+      KUBECONFIG: /home/circleci/.kube/config
+
+      MINIKUBE_WANTUPDATENOTIFICATION: false
+      MINIKUBE_WANTREPORTERRORPROMPT: false
+      MINIKUBE_HOME: /home/circleci
+      CHANGE_MINIKUBE_NONE_USER: true
+
+      USERLOCAL: /home/circleci/local
+      USERBIN: /home/circleci/local/bin
+
+      GOPATH: /home/circleci/gogo
+      GOROOT: /home/circleci/go
+      GO111MODULE: "on"
+      GO15VENDOREXPERIMENT: 1
+
   ubuntu-vm:
     working_directory: /home/circleci/gogo/src/github.com/isindir/sops-secrets-operator
     machine:
@@ -28,16 +55,22 @@ executors:
       GO15VENDOREXPERIMENT: 1
 
 jobs:
-  tools:
-    executor: ubuntu-vm
+  docker-tools:
+    executor: ubuntu-docker
     steps:
       - run:
+          name: create directories
+          command:
+            mkdir -p $USERBIN
+            mkdir -p ${HOME}/.kube
+            touch ${HOME}/.kube/config
+      - run:
           name: install golang
-          command: |
+          command:
             sudo rm -fr ${GOROOT}
             curl -sSLO https://dl.google.com/go/go${GOLANG_VERSION}.linux-amd64.tar.gz
             tar -xzf go${GOLANG_VERSION}.linux-amd64.tar.gz
-            sudo mv go /usr/local
+            sudo mv go /home/circleci/
             rm -fr go${GOLANG_VERSION}.linux-amd64.tar.gz
             mkdir -p $GOPATH/{src/github.com/isindir,bin,pkg}
             go get -u golang.org/x/lint/golint
@@ -48,43 +81,98 @@ jobs:
           command: |
             curl -sSLo kubectl https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/kubectl
             chmod +x kubectl
-            sudo mv kubectl /usr/local/bin/
-            mkdir -p ${HOME}/.kube
-            touch ${HOME}/.kube/config
+            sudo mv kubectl ${USERBIN}/
       - run:
           name: install sops
           command: |
             curl -sSLo sops https://github.com/mozilla/sops/releases/download/${SOPS_VERSION}/sops-${SOPS_VERSION}.linux
             chmod +x sops
-            sudo mv sops /usr/local/bin/
+            sudo mv sops ${USERBIN}/
       - run:
           name: install operator-sdk
           command: |
             curl -sSLo operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/${OPERATOR_SDK_VERSION}/operator-sdk-${OPERATOR_SDK_VERSION}-x86_64-linux-gnu
             chmod +x operator-sdk
-            sudo mv operator-sdk /usr/local/bin/
+            sudo mv operator-sdk ${USERBIN}/
       - run:
           name: install kind
           command: |
             curl -sSLo kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/kind-linux-amd64
             chmod +x kind
-            sudo mv kind /usr/local/bin/
+            sudo mv kind ${USERBIN}/
       #- run:
       #    name: install bats
       #    command: |
       #      sudo add-apt-repository ppa:duggan/bats
       #      sudo apt-get update
       #      sudo apt-get install bats -y
-      - run:
-          name: install gpg2
-          command: |
-            sudo apt-get update
-            sudo apt-get install gnupg2 -y
+      #- run:
+      #    name: install gpg2
+      #    command: |
+      #      sudo apt-get update
+      #      sudo apt-get install gnupg2 -y
       - save_cache:
           key: v2-bins-{{ .Branch }}
           paths:
-            - "/usr/local"
+            - "${HOME}/local"
             - "${HOME}/.kube"
+  #tools:
+  #  executor: ubuntu-vm
+  #  steps:
+  #    - run:
+  #        name: install golang
+  #        command: |
+  #          sudo rm -fr ${GOROOT}
+  #          curl -sSLO https://dl.google.com/go/go${GOLANG_VERSION}.linux-amd64.tar.gz
+  #          tar -xzf go${GOLANG_VERSION}.linux-amd64.tar.gz
+  #          sudo mv go /usr/local
+  #          rm -fr go${GOLANG_VERSION}.linux-amd64.tar.gz
+  #          mkdir -p $GOPATH/{src/github.com/isindir,bin,pkg}
+  #          go get -u golang.org/x/lint/golint
+  #          go version
+  #          go env
+  #    - run:
+  #        name: install kubectl
+  #        command: |
+  #          curl -sSLo kubectl https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/kubectl
+  #          chmod +x kubectl
+  #          sudo mv kubectl /usr/local/bin/
+  #          mkdir -p ${HOME}/.kube
+  #          touch ${HOME}/.kube/config
+  #    - run:
+  #        name: install sops
+  #        command: |
+  #          curl -sSLo sops https://github.com/mozilla/sops/releases/download/${SOPS_VERSION}/sops-${SOPS_VERSION}.linux
+  #          chmod +x sops
+  #          sudo mv sops /usr/local/bin/
+  #    - run:
+  #        name: install operator-sdk
+  #        command: |
+  #          curl -sSLo operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/${OPERATOR_SDK_VERSION}/operator-sdk-${OPERATOR_SDK_VERSION}-x86_64-linux-gnu
+  #          chmod +x operator-sdk
+  #          sudo mv operator-sdk /usr/local/bin/
+  #    - run:
+  #        name: install kind
+  #        command: |
+  #          curl -sSLo kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/kind-linux-amd64
+  #          chmod +x kind
+  #          sudo mv kind /usr/local/bin/
+  #    #- run:
+  #    #    name: install bats
+  #    #    command: |
+  #    #      sudo add-apt-repository ppa:duggan/bats
+  #    #      sudo apt-get update
+  #    #      sudo apt-get install bats -y
+  #    - run:
+  #        name: install gpg2
+  #        command: |
+  #          sudo apt-get update
+  #          sudo apt-get install gnupg2 -y
+  #    - save_cache:
+  #        key: v2-bins-{{ .Branch }}
+  #        paths:
+  #          - "/usr/local"
+  #          - "${HOME}/.kube"
   build:
     executor: ubuntu-vm
     steps:
@@ -98,121 +186,121 @@ jobs:
             - v2-modules-{{ .Branch }}-{{ checksum "go.sum" }}
             - v2-modules-{{ .Branch }}-
             - v2-modules-
-      - run:
-          name: start kind
-          command: |
-            kind create cluster
-            JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}';
-            until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do
-              sleep 1;
-            done
+      #- run:
+      #    name: start kind
+      #    command: |
+      #      kind create cluster
+      #      JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}';
+      #      until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do
+      #        sleep 1;
+      #      done
 
-            # make default account cluster-admin
-            kubectl create clusterrolebinding add-on-cluster-admin --clusterrole cluster-admin --serviceaccount=kube-system:default
+      #      # make default account cluster-admin
+      #      kubectl create clusterrolebinding add-on-cluster-admin --clusterrole cluster-admin --serviceaccount=kube-system:default
 
-            # Dump cluster info
-            kubectl cluster-info
-            kubectl version
-      - run:
-          name: setup helm and install tiller
-          command: |
-            # install helm
-            curl -sSL https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz | tar -xzvf - linux-amd64/helm
-            chmod +x linux-amd64/helm
-            sudo mv linux-amd64/helm /usr/local/bin/
-            rm -fr linux-amd64
+      #      # Dump cluster info
+      #      kubectl cluster-info
+      #      kubectl version
+      #- run:
+      #    name: setup helm and install tiller
+      #    command: |
+      #      # install helm
+      #      curl -sSL https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz | tar -xzvf - linux-amd64/helm
+      #      chmod +x linux-amd64/helm
+      #      sudo mv linux-amd64/helm /usr/local/bin/
+      #      rm -fr linux-amd64
 
-            # configure tiller
-            kubectl -n kube-system create sa tiller
-            kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
-            helm init --wait --service-account tiller
-            helm version
-      # real fun starts here
-      - run:
-          name: Fetch Go dependencies
-          command: |
-            make mod
-      - run:
-          name: Build
-          command: |
-            make build
-      - save_cache:
-          key: v2-modules-{{ .Branch }}-{{ checksum "go.sum" }}
-          paths:
-            - "/home/circleci/gogo/pkg"
-      - run:
-          name: Run Local Tests
-          command: |
-            export GNUPGHOME="$(mktemp -d)"
-            cat >$GNUPGHOME/foo \<\<EOF
-                %echo Generating a basic OpenPGP key
-                Key-Type: DSA
-                Key-Length: 1024
-                Subkey-Type: ELG-E
-                Subkey-Length: 1024
-                Name-Real: Joe Tester
-                Name-Comment: with stupid passphrase
-                Name-Email: joe@foo.bar
-                Expire-Date: 0
-                Passphrase: abc
-                %no-protection
-                %commit
-                %echo done
-            EOF
-            gpg2 --batch --gen-key $GNUPGHOME/foo
-            export SOPS_GPG_EXEC=$( which gpg2 )
-            export FP=$( gpg2 --with-colons --fingerprint | awk -F: '$1 == "fpr" {print $10; exit}' )
-            echo "Fingreprint: $FP ; gpg executable: $SOPS_GPG_EXEC"
-            # TODO: replace some of this by bash unit tests
-            # Run k8s related commands
-            kubectl create namespace sops
-            kubectl apply -f deploy/crds/isindir_v1alpha1_sopssecret_crd.yaml
-            sleep 3
-            sops -e -p $FP                    \
-              --encrypted-suffix='_templates' \
-              deploy/crds/00init.yaml         \
-              > 00init.enc.yaml
-            kubectl apply -f 00init.enc.yaml --namespace sops
-            sleep 3
-            nohup make run/local &
-            sleep 75
-            kubectl get sops --namespace sops
-            echo
-            kubectl get secrets --namespace sops
-            echo
-            export SECRETS_NUMBER=$( kubectl get secrets --namespace sops \
-              | awk '$0!~/default-token/ && $0!~/NAME/ { print $1; }' \
-              | wc -l )
-            if [[ $SECRETS_NUMBER -ne 3 ]]; then
-              echo "Expected number of secrets in sops namespace is 3 - Failed"
-              exit 1
-            fi
-            # Delete to check GC works
-            kubectl delete -f 00init.enc.yaml --namespace sops
-            sleep 15
-            kubectl get sops --namespace sops
-            echo
-            kubectl get secrets --namespace sops
-            echo
-            export SECRETS_NUMBER=$( kubectl get secrets --namespace sops \
-              | awk '$0!~/default-token/ && $0!~/NAME/ { print $1; }' \
-              | wc -l )
-            if [[ $SECRETS_NUMBER -ne 0 ]]; then
-              echo "Expected number of secrets in sops namespace is 0 - Failed"
-              exit 1
-            fi
-            rm -fr $GNUPGHOME
-      - run:
-          name: Run Tests
-          command: |
-            export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
-            make test
+      #      # configure tiller
+      #      kubectl -n kube-system create sa tiller
+      #      kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
+      #      helm init --wait --service-account tiller
+      #      helm version
+      ## real fun starts here
+      #- run:
+      #    name: Fetch Go dependencies
+      #    command: |
+      #      make mod
+      #- run:
+      #    name: Build
+      #    command: |
+      #      make build
+      #- save_cache:
+      #    key: v2-modules-{{ .Branch }}-{{ checksum "go.sum" }}
+      #    paths:
+      #      - "/home/circleci/gogo/pkg"
+      #- run:
+      #    name: Run Local Tests
+      #    command: |
+      #      export GNUPGHOME="$(mktemp -d)"
+      #      cat >$GNUPGHOME/foo \<\<EOF
+      #          %echo Generating a basic OpenPGP key
+      #          Key-Type: DSA
+      #          Key-Length: 1024
+      #          Subkey-Type: ELG-E
+      #          Subkey-Length: 1024
+      #          Name-Real: Joe Tester
+      #          Name-Comment: with stupid passphrase
+      #          Name-Email: joe@foo.bar
+      #          Expire-Date: 0
+      #          Passphrase: abc
+      #          %no-protection
+      #          %commit
+      #          %echo done
+      #      EOF
+      #      gpg2 --batch --gen-key $GNUPGHOME/foo
+      #      export SOPS_GPG_EXEC=$( which gpg2 )
+      #      export FP=$( gpg2 --with-colons --fingerprint | awk -F: '$1 == "fpr" {print $10; exit}' )
+      #      echo "Fingreprint: $FP ; gpg executable: $SOPS_GPG_EXEC"
+      #      # TODO: replace some of this by bash unit tests
+      #      # Run k8s related commands
+      #      kubectl create namespace sops
+      #      kubectl apply -f deploy/crds/isindir_v1alpha1_sopssecret_crd.yaml
+      #      sleep 3
+      #      sops -e -p $FP                    \
+      #        --encrypted-suffix='_templates' \
+      #        deploy/crds/00init.yaml         \
+      #        > 00init.enc.yaml
+      #      kubectl apply -f 00init.enc.yaml --namespace sops
+      #      sleep 3
+      #      nohup make run/local &
+      #      sleep 75
+      #      kubectl get sops --namespace sops
+      #      echo
+      #      kubectl get secrets --namespace sops
+      #      echo
+      #      export SECRETS_NUMBER=$( kubectl get secrets --namespace sops \
+      #        | awk '$0!~/default-token/ && $0!~/NAME/ { print $1; }' \
+      #        | wc -l )
+      #      if [[ $SECRETS_NUMBER -ne 3 ]]; then
+      #        echo "Expected number of secrets in sops namespace is 3 - Failed"
+      #        exit 1
+      #      fi
+      #      # Delete to check GC works
+      #      kubectl delete -f 00init.enc.yaml --namespace sops
+      #      sleep 15
+      #      kubectl get sops --namespace sops
+      #      echo
+      #      kubectl get secrets --namespace sops
+      #      echo
+      #      export SECRETS_NUMBER=$( kubectl get secrets --namespace sops \
+      #        | awk '$0!~/default-token/ && $0!~/NAME/ { print $1; }' \
+      #        | wc -l )
+      #      if [[ $SECRETS_NUMBER -ne 0 ]]; then
+      #        echo "Expected number of secrets in sops namespace is 0 - Failed"
+      #        exit 1
+      #      fi
+      #      rm -fr $GNUPGHOME
+      #- run:
+      #    name: Run Tests
+      #    command: |
+      #      export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
+      #      make test
 
 workflows:
   version: 2.1
   build_and_test:
     jobs:
-      - tools
+      - docker-tools
       - build:
           requires:
-            - tools
+            - docker-tools
